title: taskerator-gpt
email: 
description: >-
  Taskerator-GPT is based on BabyAGI which is an AI-powered task management system that uses OpenAI and Pinecone APIs to create, prioritize, and execute tasks.
baseurl: ""
url: 
logo: 
twitter_username: 
github_username:  viscountjustin
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
include: [docs]
plugins:
- jekyll-remote-theme
